import { MenuSectionData } from "./menuSection.types";

// 01. Savory Pots
export const savoryPots: MenuSectionData = {
  id: "savory-pots",
  number: "01",
  titleEn: "Savory Pots",
  titleAr: "الأطباق المالحة",
  backgroundColor: "#F7D7D5",
  accentColor: "#31451B",
  image: "/images/products/acai.webp",
  items: [
    {
      id: "sp-1",
      titleEn: "Chips & Beets Hummus",
      titleAr: "رقائق وحمص الشمندر",
      descriptionEn: "Baked za'atar chips, beetroot hummus dip",
      descriptionAr: "رقائق الزعتر المخبوزة مع غموس حمص الشمندر",
      image: "/images/products/acai.webp",
      protein: "9g",
      carbs: "28g",
      fat: "10g",
      kcal: 240,
      price: 2.25,
      available: true,
    },
    {
      id: "sp-2",
      titleEn: "Chips & Guac",
      titleAr: "رقائق وجواكامولي",
      descriptionEn: "Corn Chips, Guacamole Dip",
      descriptionAr: "رقائق الذرة مع غموس الجواكامولي",
      image: "/images/products/acai.webp",
      protein: "2g",
      carbs: "22g",
      fat: "16g",
      kcal: 240,
      price: 2.5,
      available: true,
    },
    {
      id: "sp-3",
      titleEn: "Grilled Corn",
      titleAr: "ذرة مشوية",
      descriptionEn: "Grilled corn, sour cream, lime and Parmesan cheese",
      descriptionAr: "ذرة مشوية، كريمة حامضة، ليمون وجبن بارميزان",
      image: "/images/products/acai.webp",
      protein: "6g",
      carbs: "32g",
      fat: "18g",
      kcal: 240,
      price: 2.25,
      available: true,
    },
    {
      id: "sp-4",
      titleEn: "Caesar Protein Pot",
      titleAr: "وعاء سيزر بروتين",
      descriptionEn: "Grilled chicken, lettuce, cheese and low-fat Caesar dressing",
      descriptionAr: "دجاج مشوي، خس، جبن وصلصة سيزر قليلة الدسم",
      image: "/images/products/acai.webp",
      protein: "20g",
      carbs: "6g",
      fat: "16g",
      kcal: 195,
      price: 3.25,
      available: true,
    },
    {
      id: "sp-5",
      titleEn: "Harvest Protein Pot",
      titleAr: "وعاء هارفيست بروتين",
      descriptionEn: "Grilled chicken, pumpkin, chickpeas, bulgur, black sesame, lettuce, walnuts, sesame balsamic dressing",
      descriptionAr: "دجاج مشوي، قرع، حمص، برغل، سمسم أسود، خس، جوز وصلصة بالساميك بالسمسم",
      image: "/images/products/acai.webp",
      protein: "20g",
      carbs: "14g",
      fat: "10g",
      kcal: 225,
      price: 3.5,
      available: true,
    },
    {
      id: "sp-6",
      titleEn: "Cranberry Tabbouleh Pot",
      titleAr: "وعاء تبولة الكرانبيري",
      descriptionEn: "Parsley, quinoa, tomato, spring onion, bell pepper, pine nuts and pomegranate seed with lemon mustard dressing",
      descriptionAr: "بقدونس، كينوا، طماطم، بصل أخضر، فلفل رومي، صنوبر ورمان مع صلصة الليمون والخردل",
      image: "/images/products/acai.webp",
      protein: "2g",
      carbs: "16g",
      fat: "10g",
      kcal: 275,
      price: 2.75,
      available: true,
    },
    {
      id: "sp-7",
      titleEn: "Chips & Avo Hummus",
      titleAr: "رقائق وحمص أفوكادو",
      descriptionEn: "Baked Sumac Chips, Avocado Hummus Dip",
      descriptionAr: "رقائق السماق المخبوزة مع غموس حمص الأفوكادو",
      image: "/images/products/acai.webp",
      protein: "8g",
      carbs: "28g",
      fat: "10g",
      kcal: 235,
      price: 2.5,
      available: true,
    },
  ],
};

// 02. Sweet Pots
export const sweetPots: MenuSectionData = {
  id: "sweet-pots",
  number: "02",
  titleEn: "Sweet Pots",
  titleAr: "الأطباق الحلوة",
  backgroundColor: "#F7E9C9",
  accentColor: "#8B5A2B",
  image: "/images/products/matcha.webp",
  items: [
    {
      id: "swp-1",
      titleEn: "Peanut Oatmeal",
      titleAr: "شوفان بزبدة الفول السوداني",
      descriptionEn: "Peanut butter, oatmeal, chia pudding, banana, biscuit",
      descriptionAr: "زبدة فول سوداني، شوفان، بودينغ الشيا، موز وبسكويت",
      image: "/images/products/matcha.webp",
      protein: "10g",
      carbs: "25g",
      fat: "15g",
      kcal: 255,
      price: 2.75,
      available: true,
    },
    {
      id: "swp-2",
      titleEn: "Banana Oatmeal Pot",
      titleAr: "وعاء شوفان بالموز",
      descriptionEn: "Banana-biscuit, oatmeal, chia pudding and pecan",
      descriptionAr: "بسكويت بالموز، شوفان، بودينغ الشيا وجوز البيكان",
      image: "/images/products/matcha.webp",
      protein: "10g",
      carbs: "25g",
      fat: "13g",
      kcal: 255,
      price: 2.75,
      available: true,
    },
    {
      id: "swp-3",
      titleEn: "Blueberry Oatmeal Pot",
      titleAr: "وعاء شوفان بالتوت الأزرق",
      descriptionEn: "Blueberry biscuit jam, oatmeal, chia pudding and pistachio",
      descriptionAr: "مربى بسكويت التوت الأزرق، شوفان، بودينغ الشيا وفستق",
      image: "/images/products/matcha.webp",
      protein: "18g",
      carbs: "28g",
      fat: "10g",
      kcal: 240,
      price: 2.95,
      available: true,
    },
    {
      id: "swp-4",
      titleEn: "Power Pot Mango",
      titleAr: "وعاء باور مانجو",
      descriptionEn: "Low-fat Greek yogurt with honey, mango and granola",
      descriptionAr: "زبادي يوناني قليل الدسم مع العسل والمانجو والجرانولا",
      image: "/images/products/matcha.webp",
      protein: "15g",
      carbs: "26g",
      fat: "6g",
      kcal: 220,
      price: 3.25,
      available: true,
    },
    {
      id: "swp-5",
      titleEn: "Power Pot Berries",
      titleAr: "وعاء باور توت",
      descriptionEn: "Low-fat greek yogurt with honey, mixed berries and granola",
      descriptionAr: "زبادي يوناني قليل الدسم مع العسل والتوت المشكل والجرانولا",
      image: "/images/products/matcha.webp",
      protein: "15g",
      carbs: "26g",
      fat: "6g",
      kcal: 220,
      price: 3.25,
      available: true,
    },
    {
      id: "swp-6",
      titleEn: "Tropical Açaí",
      titleAr: "أساي استوائي",
      descriptionEn: "Açaí, granola, mixed berries and mango",
      descriptionAr: "أساي، جرانولا، توت مشكل ومانجو",
      image: "/images/products/matcha.webp",
      protein: "4g",
      carbs: "56g",
      fat: "10g",
      kcal: 330,
      price: 3.75,
      available: true,
    },
    {
      id: "swp-7",
      titleEn: "Açaí Peanut Butter",
      titleAr: "أساي زبدة الفول السوداني",
      descriptionEn: "Açaí, granola, raspberries, banana, and peanut butter",
      descriptionAr: "أساي، جرانولا، توت علق، موز وزبدة الفول السوداني",
      image: "/images/products/matcha.webp",
      protein: "12g",
      carbs: "53g",
      fat: "20g",
      kcal: 440,
      price: 3.95,
      available: true,
    },
    {
      id: "swp-8",
      titleEn: "Classic Cheese Puff",
      titleAr: "فطيرة الجبن الكلاسيكية",
      descriptionEn: "Ananas house blend cheese, white sesame with brown dough",
      descriptionAr: "خليط أجبان أناناس، سمسم أبيض مع عجينة بر",
      image: "/images/products/matcha.webp",
      protein: "15g",
      carbs: "35g",
      fat: "18g",
      kcal: 368,
      price: 2.25,
      available: true,
    },
    {
      id: "swp-9",
      titleEn: "Pizza Puff",
      titleAr: "فطيرة البيتزا",
      descriptionEn: "Pizza sauce, cheese with white dough",
      descriptionAr: "صلصة البيتزا والجبن مع عجينة بيضاء",
      image: "/images/products/matcha.webp",
      protein: "10g",
      carbs: "46g",
      fat: "16g",
      kcal: 370,
      price: 2.25,
      available: true,
    },
    {
      id: "swp-10",
      titleEn: "Za'atar Cheese Puff",
      titleAr: "فطيرة زعتر وجبن",
      descriptionEn: "Za'atar, halloumi cheese, brown dough",
      descriptionAr: "زعتر، جبنة حلوم وعجينة بر",
      image: "/images/products/matcha.webp",
      protein: "15g",
      carbs: "35g",
      fat: "18g",
      kcal: 360,
      price: 2.25,
      available: true,
    },
  ],
};

// 03. Salads
export const salads: MenuSectionData = {
  id: "salads",
  number: "03",
  titleEn: "Salads",
  titleAr: "السلطات",
  backgroundColor: "#E2EAD2",
  accentColor: "#2A4023",
  image: "/images/products/salad.webp",
  items: [
    {
      id: "sal-1",
      titleEn: "Mango Salad",
      titleAr: "سلطة المانجو",
      descriptionEn: "Mango, edamame, cabbage, carrot, sesame, sweet and sour dressing",
      descriptionAr: "مانجو، إدامامي، ملفوف، جزر، سمسم وصلصة حامض وحلو",
      image: "/images/products/salad.webp",
      protein: "4g",
      carbs: "22g",
      fat: "8g",
      kcal: 199,
      price: 3.25,
      available: true,
    },
    {
      id: "sal-2",
      titleEn: "Sesame Salad",
      titleAr: "سلطة السمسم",
      descriptionEn: "Quinoa, kale, sesame, apple, carrot and sesame dressing",
      descriptionAr: "كينوا، كيل، سمسم، تفاح، جزر وصلصة السمسم",
      image: "/images/products/salad.webp",
      protein: "4g",
      carbs: "14g",
      fat: "16g",
      kcal: 215,
      price: 3.5,
      available: true,
    },
    {
      id: "sal-3",
      titleEn: "Beetroot Salad",
      titleAr: "سلطة الشمندر",
      descriptionEn: "Beetroot, lettuce, cheese, pine nuts and pink balsamic dressing",
      descriptionAr: "شمندر، خس، جبن، صنوبر وصلصة البالساميك الوردية",
      image: "/images/products/salad.webp",
      protein: "3g",
      carbs: "18g",
      fat: "15g",
      kcal: 220,
      price: 3.25,
      available: true,
    },
    {
      id: "sal-4",
      titleEn: "Chicken Caesar Salad",
      titleAr: "سلطة دجاج سيزر",
      descriptionEn: "Lettuce, kale, chicken, cheese and caesar sauce",
      descriptionAr: "خس، كيل، دجاج، جبن وصلصة سيزر",
      image: "/images/products/salad.webp",
      protein: "35g",
      carbs: "12g",
      fat: "20g",
      kcal: 370,
      price: 3.95,
      available: true,
    },
    {
      id: "sal-5",
      titleEn: "Chicken Harvest Salad",
      titleAr: "سلطة دجاج هارفيست",
      descriptionEn: "Grilled chicken, roasted pumpkin, bulgur, black sesame, mixed green leaves, walnuts and sesame balsamic dressing",
      descriptionAr: "دجاج مشوي، قرع محمص، برغل، سمسم أسود، أوراق خضراء مشكلة، جوز وصلصة بالساميك بالسمسم",
      image: "/images/products/salad.webp",
      protein: "35g",
      carbs: "20g",
      fat: "16g",
      kcal: 370,
      price: 3.95,
      available: true,
    },
    {
      id: "sal-6",
      titleEn: "Cranberry Tabbouleh Salad",
      titleAr: "سلطة تبولة الكرانبيري",
      descriptionEn: "Parsley, quinoa, tomato, spring onion, bell pepper, pine nuts and pomegranate seed with lemon mustard dressing",
      descriptionAr: "بقدونس، كينوا، طماطم، بصل أخضر، فلفل رومي، صنوبر ورمان مع صلصة الليمون والخردل",
      image: "/images/products/salad.webp",
      protein: "5g",
      carbs: "24g",
      fat: "20g",
      kcal: 305,
      price: 3.25,
      available: true,
    },
    {
      id: "sal-7",
      titleEn: "Corn Salad",
      titleAr: "سلطة الذرة",
      descriptionEn: "Grilled corn, jalapeno, baby gem, parsley, parmesan cheese, croutons, caesar dressing",
      descriptionAr: "ذرة مشوية، هالابينو، خس بيبي جيم، بقدونس، جبن بارميزان، خبز محمص وصلصة سيزر",
      image: "/images/products/salad.webp",
      protein: "6g",
      carbs: "28g",
      fat: "16g",
      kcal: 288,
      price: 3.25,
      available: true,
    },
  ],
};

// 04. Sandwiches & Wraps
export const sandwichesWraps: MenuSectionData = {
  id: "sandwiches-wraps",
  number: "04",
  titleEn: "Sandwiches & Wraps",
  titleAr: "السندويشات واللفائف",
  backgroundColor: "#EBDAD3",
  accentColor: "#42281D",
  image: "/images/products/sandwich.webp",
  items: [
    {
      id: "sw-1",
      titleEn: "Chicken Club Sandwich",
      titleAr: "سندويش كلوب دجاج",
      descriptionEn: "Multigrain sourdough, chicken, turkey, cheese, pickles and creamy mustard",
      descriptionAr: "خبز ساوردو حبوب كاملة، دجاج، تركي، جبن، مخلل وخردل كريمي",
      image: "/images/products/sandwich.webp",
      protein: "38g",
      carbs: "40g",
      fat: "18g",
      kcal: 440,
      price: 3.75,
      available: true,
    },
    {
      id: "sw-2",
      titleEn: "Beets & Halloumi Sandwich",
      titleAr: "سندويش الشمندر والحلومي",
      descriptionEn: "Sourdough bread, olives, beetroot carpaccio, halloumi, beetroot hummus, rocca leaves and pesto sauce",
      descriptionAr: "خبز ساوردو، زيتون، كرباتشيو الشمندر، حلوم، حمص الشمندر، جرجير وصلصة البيستو",
      image: "/images/products/sandwich.webp",
      protein: "18g",
      carbs: "42g",
      fat: "16g",
      kcal: 385,
      price: 3.25,
      available: true,
    },
    {
      id: "sw-3",
      titleEn: "Chicken Guacamole Sandwich",
      titleAr: "سندويش دجاج جواكامولي",
      descriptionEn: "Chicken, guacamole and cheese",
      descriptionAr: "دجاج، جواكامولي وجبن",
      image: "/images/products/sandwich.webp",
      protein: "30g",
      carbs: "40g",
      fat: "18g",
      kcal: 440,
      price: 3.5,
      available: true,
    },
    {
      id: "sw-4",
      titleEn: "Halloumi Cheese Sandwich",
      titleAr: "سندويش جبن الحلوم",
      descriptionEn: "Halloumi, Kalamata olive paste, tomato, pesto",
      descriptionAr: "حلوم، معجون زيتون كلاماتا، طماطم، بيستو",
      image: "/images/products/sandwich.webp",
      protein: "18g",
      carbs: "40g",
      fat: "16g",
      kcal: 375,
      price: 3.25,
      available: true,
    },
    {
      id: "sw-5",
      titleEn: "Turkey Sandwich",
      titleAr: "سندويش التركي",
      descriptionEn: "Turkey, cheese, tomato and caramelized grape",
      descriptionAr: "تركي، جبن، طماطم وعنب مكرمل",
      image: "/images/products/sandwich.webp",
      protein: "30g",
      carbs: "48g",
      fat: "15g",
      kcal: 415,
      price: 3.5,
      available: true,
    },
    {
      id: "sw-6",
      titleEn: "Chicken Wrap",
      titleAr: "رول الدجاج",
      descriptionEn: "Chicken, pickles, potato and tortilla",
      descriptionAr: "دجاج، مخلل، بطاطس وخبز التورتيلا",
      image: "/images/products/sandwich.webp",
      protein: "36g",
      carbs: "36g",
      fat: "10g",
      kcal: 355,
      price: 3.25,
      available: true,
    },
    {
      id: "sw-7",
      titleEn: "Beef Tenderloin Wrap",
      titleAr: "رول لحم تندرلوين",
      descriptionEn: "Tenderloin beef, potato, pickles, tortilla and tahini sauce",
      descriptionAr: "لحم تندرلوين، بطاطس، مخلل، تورتيلا وصلصة الطحينة",
      image: "/images/products/sandwich.webp",
      protein: "25g",
      carbs: "36g",
      fat: "14g",
      kcal: 370,
      price: 3.95,
      available: true,
    },
    {
      id: "sw-8",
      titleEn: "Falafel Wrap",
      titleAr: "رول الفلافل",
      descriptionEn: "Falafel, potato, cucumber, cabbage, tahini, tortilla",
      descriptionAr: "فلافل، بطاطس، خيار، ملفوف، طحينة، تورتيلا",
      image: "/images/products/sandwich.webp",
      protein: "10g",
      carbs: "48g",
      fat: "16g",
      kcal: 375,
      price: 2.75,
      available: true,
    },
    {
      id: "sw-9",
      titleEn: "Labneh Focaccia",
      titleAr: "فوكادشيا اللبنة",
      descriptionEn: "Focaccia, labneh, zataar, tomato, kalamata olives",
      descriptionAr: "فوكادشيا، لبنة، زعتر، طماطم، زيتون كلاماتا",
      image: "/images/products/sandwich.webp",
      protein: "12g",
      carbs: "52g",
      fat: "15g",
      kcal: 390,
      price: 2.95,
      available: true,
    },
  ],
};

// 05. Buns & Tacos
export const bunsTacos: MenuSectionData = {
  id: "buns-tacos",
  number: "05",
  titleEn: "Buns & Tacos",
  titleAr: "البنز والتاكو",
  backgroundColor: "#F2E2C6",
  accentColor: "#593D1E",
  image: "/images/products/tacos.webp",
  items: [
    {
      id: "bt-1",
      titleEn: "Simit Bun",
      titleAr: "بن السميط",
      descriptionEn: "Sesame simit bun, mix cheese, emmental, tomato, guacamole",
      descriptionAr: "بن سميط بالسمسم، جبن مشكل، إمنتال، طماطم، جواكامولي",
      image: "/images/products/tacos.webp",
      protein: "15g",
      carbs: "35g",
      fat: "16g",
      kcal: 344,
      price: 2.95,
      available: true,
    },
    {
      id: "bt-2",
      titleEn: "Spicy Club Bun",
      titleAr: "سبايسي كلوب بن",
      descriptionEn: "Oat brown bun, chicken, turkey, cheese, guac, jalapeno and creamy mustard",
      descriptionAr: "بن بر بالشوفان، دجاج، تركي، جبن، جواكامولي، هالابينو وخردل كريمي",
      image: "/images/products/tacos.webp",
      protein: "30g",
      carbs: "38g",
      fat: "18g",
      kcal: 408,
      price: 3.5,
      available: true,
    },
    {
      id: "bt-3",
      titleEn: "Buffalo Chicken Bun",
      titleAr: "بافالو دجاج بن",
      descriptionEn: "Oats brown bun, chicken, white cheese, celery sauce",
      descriptionAr: "بن بر بالشوفان، دجاج، جبن أبيض، صلصة الكرفس",
      image: "/images/products/tacos.webp",
      protein: "30g",
      carbs: "30g",
      fat: "15g",
      kcal: 375,
      price: 3.5,
      available: true,
    },
    {
      id: "bt-4",
      titleEn: "Halloumi Beets Bun",
      titleAr: "حلوم بالشمندر بن",
      descriptionEn: "Za'atar brown bun, halloumi, beetroot, rocca, beetroot sauce and green olive paste",
      descriptionAr: "بن بر بالزعتر، حلوم، شمندر، جرجير، صلصة الشمندر ومعجون الزيتون الأخضر",
      image: "/images/products/tacos.webp",
      protein: "15g",
      carbs: "32g",
      fat: "12g",
      kcal: 296,
      price: 3.25,
      available: true,
    },
    {
      id: "bt-5",
      titleEn: "Chicken Guac Tacos",
      titleAr: "تاكو الدجاج والجواكامولي",
      descriptionEn: "Pita taco, grilled chicken, guacamole, corn and sriracha sour cream",
      descriptionAr: "تاكو بيتا، دجاج مشوي، جواكامولي، ذرة وسريراتشا كريمة حامضة",
      image: "/images/products/tacos.webp",
      protein: "28g",
      carbs: "34g",
      fat: "12g",
      kcal: 325,
      price: 3.75,
      available: true,
    },
    {
      id: "bt-6",
      titleEn: "Shrimp Tacos",
      titleAr: "تاكو الروبيان",
      descriptionEn: "Pita tacos, grilled shrimp and tartar sauce",
      descriptionAr: "تاكو بيتا، روبيان مشوي وصلصة التارتار",
      image: "/images/products/tacos.webp",
      protein: "15g",
      carbs: "34g",
      fat: "10g",
      kcal: 285,
      price: 3.95,
      available: true,
    },
    {
      id: "bt-7",
      titleEn: "Ribs Tacos",
      titleAr: "تاكو الأضلاع",
      descriptionEn: "Pita taco, beef, creamy mustard and pickles",
      descriptionAr: "تاكو بيتا، لحم بقر، خردل كريمي ومخلل",
      image: "/images/products/tacos.webp",
      protein: "20g",
      carbs: "42g",
      fat: "15g",
      kcal: 385,
      price: 4.25,
      available: true,
    },
  ],
};

// 06. Plates
export const plates: MenuSectionData = {
  id: "plates",
  number: "06",
  titleEn: "Plates",
  titleAr: "الأطباق الرئيسية",
  backgroundColor: "#E8DFD8",
  accentColor: "#3B2A22",
  image: "/images/products/plate.webp",
  items: [
    {
      id: "pl-1",
      titleEn: "Chicken & Rice",
      titleAr: "دجاج وأرز",
      descriptionEn: "Saffron basmati rice, grilled chicken, tomato gravy & ginger yoghurt sauce",
      descriptionAr: "أرز بسمتي بالزعفران، دجاج مشوي، صلصة الطماطم وصلصة الزبادي والزنجبيل",
      image: "/images/products/plate.webp",
      protein: "50g",
      carbs: "50g",
      fat: "12g",
      kcal: 545,
      price: 4.5,
      available: true,
    },
    {
      id: "pl-2",
      titleEn: "Shrimp & Rice",
      titleAr: "روبيان وأرز",
      descriptionEn: "Murabian, herb basmati rice, steamed shrimp, tomato daqoos and tamarind sauce",
      descriptionAr: "مربين، أرز بسمتي بالأعشاب، روبيان مطهو بالبخار، دقوس طماطم وصلصة التمر الهندي",
      image: "/images/products/plate.webp",
      protein: "35g",
      carbs: "58g",
      fat: "12g",
      kcal: 450,
      price: 4.95,
      available: true,
    },
    {
      id: "pl-3",
      titleEn: "Chicken & Mash",
      titleAr: "دجاج وبطاطس مهروسة",
      descriptionEn: "Grilled chicken, mashed potato, mixed vegetables, mushroom gravy",
      descriptionAr: "دجاج مشوي، بطاطس مهروسة، خضار مشكلة، مرق الفطر",
      image: "/images/products/plate.webp",
      protein: "45g",
      carbs: "40g",
      fat: "15g",
      kcal: 540,
      price: 4.5,
      available: true,
    },
    {
      id: "pl-4",
      titleEn: "Chicken Biryani",
      titleAr: "برياني دجاج",
      descriptionEn: "Chicken biryani with mint sauce and yogurt sauce",
      descriptionAr: "برياني دجاج مع صلصة النعناع وصلصة الزبادي",
      image: "/images/products/plate.webp",
      protein: "50g",
      carbs: "58g",
      fat: "12g",
      kcal: 620,
      price: 4.75,
      available: true,
    },
    {
      id: "pl-5",
      titleEn: "Chicken Burrito",
      titleAr: "بوريتو الدجاج",
      descriptionEn: "Grilled chicken, black beans, corn, rice, and guacamole",
      descriptionAr: "دجاج مشوي، فاصولياء سوداء، ذرة، أرز، وجواكامولي",
      image: "/images/products/plate.webp",
      protein: "55g",
      carbs: "60g",
      fat: "20g",
      kcal: 660,
      price: 4.5,
      available: true,
    },
    {
      id: "pl-6",
      titleEn: "Paprika Chicken",
      titleAr: "دجاج بابريكا",
      descriptionEn: "Lemon chicken, cilantro rice, yogurt sauce",
      descriptionAr: "دجاج بالليمون، أرز كزبرة، صلصة الزبادي",
      image: "/images/products/plate.webp",
      protein: "55g",
      carbs: "50g",
      fat: "10g",
      kcal: 510,
      price: 4.25,
      available: true,
    },
    {
      id: "pl-7",
      titleEn: "Mushroom Chicken",
      titleAr: "دجاج بالفطر",
      descriptionEn: "Grilled chicken, risotto rice, broccoli, pink mushroom sauce",
      descriptionAr: "دجاج مشوي، أرز ريزوتو، بروكلي، صلصة الفطر الوردية",
      image: "/images/products/plate.webp",
      protein: "50g",
      carbs: "55g",
      fat: "15g",
      kcal: 620,
      price: 4.75,
      available: true,
    },
    {
      id: "pl-8",
      titleEn: "Baby Corn Beef",
      titleAr: "لحم بقر مع الذرة الصغيرة",
      descriptionEn: "Tenderloin beef, soya, mix vegetables and white rice",
      descriptionAr: "لحم تندرلوين، صويا، خضار مشكلة وأرز أبيض",
      image: "/images/products/plate.webp",
      protein: "48g",
      carbs: "55g",
      fat: "15g",
      kcal: 555,
      price: 4.95,
      available: true,
    },
    {
      id: "pl-9",
      titleEn: "Okra & Ribs",
      titleAr: "بامية وأضلاع",
      descriptionEn: "Short ribs, okra, potato, white rice",
      descriptionAr: "أضلاع قصيرة، بامية، بطاطس، أرز أبيض",
      image: "/images/products/plate.webp",
      protein: "46g",
      carbs: "35g",
      fat: "18g",
      kcal: 540,
      price: 5.25,
      available: true,
    },
    {
      id: "pl-10",
      titleEn: "Butter Chicken",
      titleAr: "بتر تشيكن",
      descriptionEn: "Grilled chicken breast, tomatoes-based curry, cream and white rice",
      descriptionAr: "صدر دجاج مشوي، كاري طماطم، كريمة وأرز أبيض",
      image: "/images/products/plate.webp",
      protein: "45g",
      carbs: "56g",
      fat: "16g",
      kcal: 590,
      price: 4.5,
      available: true,
    },
    {
      id: "pl-11",
      titleEn: "Penne Arrabbiata Pasta",
      titleAr: "باستا بيني أرابياتا",
      descriptionEn: "Arrabbiata penne pasta, sun-dried tomato, halloumi cheese, olives and tomato sauce",
      descriptionAr: "باستا بيني أرابياتا، طماطم مجففة، جبن حلوم، زيتون وصلصة طماطم",
      image: "/images/products/plate.webp",
      protein: "15g",
      carbs: "56g",
      fat: "14g",
      kcal: 445,
      price: 3.75,
      available: true,
    },
    {
      id: "pl-12",
      titleEn: "Alfredo Chicken Pasta",
      titleAr: "باستا دجاج الفريدو",
      descriptionEn: "Penne pasta, cheese, chicken alfredo sauce with mushrooms",
      descriptionAr: "باستا بيني، جبن، صلصة دجاج الفريدو مع الفطر",
      image: "/images/products/plate.webp",
      protein: "35g",
      carbs: "50g",
      fat: "24g",
      kcal: 555,
      price: 4.25,
      available: true,
    },
    {
      id: "pl-13",
      titleEn: "Pink Pasta Chicken",
      titleAr: "باستا دجاج بالصلصة الوردية",
      descriptionEn: "Fusilli pasta, pink sauce, chicken, cheese and broccoli",
      descriptionAr: "باستا فوزيلي، صلصة وردية، دجاج، جبن وبروكلي",
      image: "/images/products/plate.webp",
      protein: "35g",
      carbs: "50g",
      fat: "15g",
      kcal: 499,
      price: 4.25,
      available: true,
    },
    {
      id: "pl-14",
      titleEn: "Beef & Mash",
      titleAr: "لحم بقر وبطاطس مهروسة",
      descriptionEn: "Beef tenderloin, mashed potato and yogurt sauce",
      descriptionAr: "لحم تندرلوين، بطاطس مهروسة وصلصة الزبادي",
      image: "/images/products/plate.webp",
      protein: "20g",
      carbs: "26g",
      fat: "16g",
      kcal: 330,
      price: 4.5,
      available: true,
    },
    {
      id: "pl-15",
      titleEn: "Grilled Chicken",
      titleAr: "دجاج مشوي",
      descriptionEn: "Grilled chicken and low-fat cilantro ranch dip",
      descriptionAr: "دجاج مشوي مع غموس رانش الكزبرة قليل الدسم",
      image: "/images/products/plate.webp",
      protein: "35g",
      carbs: "5g",
      fat: "7g",
      kcal: 265,
      price: 3.5,
      available: true,
    },
    {
      id: "pl-16",
      titleEn: "Grilled Shrimp",
      titleAr: "روبيان مشوي",
      descriptionEn: "Grilled shrimp and tartar sauce",
      descriptionAr: "روبيان مشوي وصلصة التارتار",
      image: "/images/products/plate.webp",
      protein: "30g",
      carbs: "4g",
      fat: "8g",
      kcal: 220,
      price: 3.95,
      available: true,
    },
    {
      id: "pl-17",
      titleEn: "Roasted Potato",
      titleAr: "بطاطس محمصة",
      descriptionEn: "Roasted Potato, low-fat honey mustard sauce",
      descriptionAr: "بطاطس محمصة مع صلصة الخردل والعسل قليلة الدسم",
      image: "/images/products/plate.webp",
      protein: "4g",
      carbs: "48g",
      fat: "6g",
      kcal: 280,
      price: 1.95,
      available: true,
    },
  ],
};

// 07. Juices
export const juices: MenuSectionData = {
  id: "juices",
  number: "07",
  titleEn: "Juices",
  titleAr: "العصائر",
  backgroundColor: "#FBE6C2",
  accentColor: "#6A4518",
  image: "/images/products/juice.webp",
  items: [
    {
      id: "jc-1",
      titleEn: "Orange Juice",
      titleAr: "عصير برتقال",
      descriptionEn: "Fresh Orange",
      descriptionAr: "برتقال طازج",
      image: "/images/products/juice.webp",
      protein: "0g",
      carbs: "34g",
      fat: "0g",
      kcal: 135,
      price: 1.75,
      available: true,
    },
    {
      id: "jc-2",
      titleEn: "Pacific Green Juice",
      titleAr: "عصير باسيفيك الجرين",
      descriptionEn: "Pineapple, apple, kale, mint",
      descriptionAr: "أناناس، تفاح، كيل، نعناع",
      image: "/images/products/juice.webp",
      protein: "8g",
      carbs: "38g",
      fat: "0g",
      kcal: 150,
      price: 2.25,
      available: true,
    },
    {
      id: "jc-3",
      titleEn: "PAC Juice",
      titleAr: "عصير باك",
      descriptionEn: "Passion fruit, apple, pineapple, celery",
      descriptionAr: "باDirectory فروت، تفاح، أناناس، كرفس",
      image: "/images/products/juice.webp",
      protein: "0g",
      carbs: "34g",
      fat: "0g",
      kcal: 135,
      price: 2.25,
      available: true,
    },
  ],
};

// 08. Detox
export const detox: MenuSectionData = {
  id: "detox",
  number: "08",
  titleEn: "Detox",
  titleAr: "ديتوكس",
  backgroundColor: "#E4EED8",
  accentColor: "#2F4A1B",
  image: "/images/products/detox.webp",
  items: [
    {
      id: "dtx-1",
      titleEn: "Morning Dew Detox",
      titleAr: "ديتوكس ندى الصباح",
      descriptionEn: "Carrot, orange, apple, ginger",
      descriptionAr: "جزر، برتقال، تفاح، زنجبيل",
      image: "/images/products/detox.webp",
      protein: "0g",
      carbs: "32g",
      fat: "0g",
      kcal: 145,
      price: 2.25,
      available: true,
    },
    {
      id: "dtx-2",
      titleEn: "Ruby Red Detox",
      titleAr: "ديتوكس روبي ريد",
      descriptionEn: "Beetroot, pomegranate, ginger, apple",
      descriptionAr: "شمندر، رمان، زنجبيل، تفاح",
      image: "/images/products/detox.webp",
      protein: "0g",
      carbs: "32g",
      fat: "0g",
      kcal: 145,
      price: 2.25,
      available: true,
    },
    {
      id: "dtx-3",
      titleEn: "Ginger Shot",
      titleAr: "شوت الزنجبيل",
      descriptionEn: "Ginger, lemon, apple",
      descriptionAr: "زنجبيل، ليمون، تفاح",
      image: "/images/products/detox.webp",
      protein: "0g",
      carbs: "12g",
      fat: "0g",
      kcal: 50,
      price: 1.25,
      available: true,
    },
  ],
};

// 09. Lushies
export const lushies: MenuSectionData = {
  id: "lushies",
  number: "09",
  titleEn: "Lushies",
  titleAr: "لاشيز",
  backgroundColor: "#FCE1D6",
  accentColor: "#752E1B",
  image: "/images/products/lushies.webp",
  items: [
    {
      id: "lsh-1",
      titleEn: "Equalush Lush",
      titleAr: "إيكوالاش لاش",
      descriptionEn: "Mango and passion fruit",
      descriptionAr: "مانجو وباDirectory فروت",
      image: "/images/products/lushies.webp",
      protein: "0g",
      carbs: "36g",
      fat: "0g",
      kcal: 180,
      price: 2.5,
      available: true,
    },
    {
      id: "lsh-2",
      titleEn: "Pinacoco Lush",
      titleAr: "بيناكوكو لاش",
      descriptionEn: "Pineapple, coconut",
      descriptionAr: "أناناس، جوز الهند",
      image: "/images/products/lushies.webp",
      protein: "0g",
      carbs: "38g",
      fat: "0g",
      kcal: 190,
      price: 2.5,
      available: true,
    },
    {
      id: "lsh-3",
      titleEn: "Pom & Berries Lush",
      titleAr: "رمان وتوت لاش",
      descriptionEn: "Pomegranate and mixed berries",
      descriptionAr: "رمان وتوت مشكل",
      image: "/images/products/lushies.webp",
      protein: "0g",
      carbs: "36g",
      fat: "0g",
      kcal: 180,
      price: 2.5,
      available: true,
    },
    {
      id: "lsh-4",
      titleEn: "Caribbean Lush",
      titleAr: "كاريبين لاش",
      descriptionEn: "Pinacoco and mango",
      descriptionAr: "بيناكوكو ومانجو",
      image: "/images/products/lushies.webp",
      protein: "0g",
      carbs: "38g",
      fat: "0g",
      kcal: 195,
      price: 2.75,
      available: true,
    },
    {
      id: "lsh-5",
      titleEn: "Hawaiian Lush",
      titleAr: "هاوايان لاش",
      descriptionEn: "Berries, pineapple, coconut, mango",
      descriptionAr: "توت، أناناس، جوز الهند، مانجو",
      image: "/images/products/lushies.webp",
      protein: "0g",
      carbs: "40g",
      fat: "0g",
      kcal: 200,
      price: 2.75,
      available: true,
    },
    {
      id: "lsh-6",
      titleEn: "Matcha Lush",
      titleAr: "ماتشا لاش",
      descriptionEn: "Matcha, vanilla",
      descriptionAr: "ماتشا، فانيلا",
      image: "/images/products/lushies.webp",
      protein: "0g",
      carbs: "32g",
      fat: "0g",
      kcal: 160,
      price: 2.75,
      available: true,
    },
    {
      id: "lsh-7",
      titleEn: "Matcha Berries",
      titleAr: "ماتشا بالتوت",
      descriptionEn: "Matcha, vanilla, mixed berries",
      descriptionAr: "ماتشا، فانيلا، توت مشكل",
      image: "/images/products/lushies.webp",
      protein: "0g",
      carbs: "36g",
      fat: "0g",
      kcal: 180,
      price: 2.95,
      available: true,
    },
  ],
};

// 10. Coffee
export const coffee: MenuSectionData = {
  id: "coffee",
  number: "10",
  titleEn: "Coffee",
  titleAr: "القهوة",
  backgroundColor: "#E2D9CD",
  accentColor: "#3D2E20",
  image: "/images/products/coffee.webp",
  items: [
    {
      id: "cof-1",
      titleEn: "Cold Brew",
      titleAr: "كولد بريو",
      descriptionEn: "24 Hours Brew",
      descriptionAr: "مقطرة لمدة 24 ساعة",
      image: "/images/products/coffee.webp",
      protein: "0g",
      carbs: "0g",
      fat: "0g",
      kcal: 10,
      price: 2.25,
      available: true,
    },
    {
      id: "cof-2",
      titleEn: "Americano",
      titleAr: "أمريكانو",
      descriptionEn: "Double Espresso and water",
      descriptionAr: "إسبريسو مضاعف وماء",
      image: "/images/products/coffee.webp",
      protein: "0g",
      carbs: "0g",
      fat: "0g",
      kcal: 10,
      price: 1.5,
      available: true,
    },
    {
      id: "cof-3",
      titleEn: "Iced Espresso (Small)",
      titleAr: "إسبريسو بارد (صغير)",
      descriptionEn: "Classic espresso or flavored, double espresso",
      descriptionAr: "إسبريسو كلاسيك أو بنكهة، إسبريسو مضاعف",
      image: "/images/products/coffee.webp",
      protein: "0g",
      carbs: "12g",
      fat: "0g",
      kcal: 58,
      price: 1.75,
      available: true,
    },
    {
      id: "cof-4",
      titleEn: "Iced Espresso (Regular)",
      titleAr: "إسبريسو بارد (وسط)",
      descriptionEn: "Classic espresso or flavored, double espresso",
      descriptionAr: "إسبريسو كلاسيك أو بنكهة، إسبريسو مضاعف",
      image: "/images/products/coffee.webp",
      protein: "0g",
      carbs: "18g",
      fat: "0g",
      kcal: 75,
      price: 2.0,
      available: true,
    },
    {
      id: "cof-5",
      titleEn: "Latte",
      titleAr: "لاتيه",
      descriptionEn: "Fresh milk, double espresso",
      descriptionAr: "حليب طازج، إسبريسو مضاعف",
      image: "/images/products/coffee.webp",
      protein: "4g",
      carbs: "15g",
      fat: "5g",
      kcal: 135,
      price: 2.0,
      available: true,
    },
    {
      id: "cof-6",
      titleEn: "Cappuccino",
      titleAr: "كابوتشينو",
      descriptionEn: "Foam, milk and double espresso",
      descriptionAr: "رغوة، حليب وإسبريسو مضاعف",
      image: "/images/products/coffee.webp",
      protein: "4g",
      carbs: "12g",
      fat: "3g",
      kcal: 118,
      price: 2.0,
      available: true,
    },
    {
      id: "cof-7",
      titleEn: "Flat White",
      titleAr: "فلات وايت",
      descriptionEn: "Fresh milk, double espresso",
      descriptionAr: "حليب طازج، إسبريسو مضاعف",
      image: "/images/products/coffee.webp",
      protein: "5g",
      carbs: "10g",
      fat: "3g",
      kcal: 95,
      price: 2.0,
      available: true,
    },
    {
      id: "cof-8",
      titleEn: "Spanish Latte",
      titleAr: "سبانيش لاتيه",
      descriptionEn: "Condensed milk, double espresso, fresh milk",
      descriptionAr: "حليب مكثف، إسبريسو مضاعف، حليب طازج",
      image: "/images/products/coffee.webp",
      protein: "5g",
      carbs: "36g",
      fat: "9g",
      kcal: 245,
      price: 2.25,
      available: true,
    },
    {
      id: "cof-9",
      titleEn: "Cubano",
      titleAr: "كوبانو",
      descriptionEn: "Toffee nut latte, double espresso, fresh milk",
      descriptionAr: "لاتيه التوفي جوز، إسبريسو مضاعف، حليب طازج",
      image: "/images/products/coffee.webp",
      protein: "5g",
      carbs: "34g",
      fat: "9g",
      kcal: 235,
      price: 2.25,
      available: true,
    },
    {
      id: "cof-10",
      titleEn: "Coco",
      titleAr: "كوكو",
      descriptionEn: "Coconut latte, double espresso, fresh milk",
      descriptionAr: "لاتيه جوز الهند، إسبريسو مضاعف، حليب طازج",
      image: "/images/products/coffee.webp",
      protein: "5g",
      carbs: "32g",
      fat: "9g",
      kcal: 230,
      price: 2.25,
      available: true,
    },
    {
      id: "cof-11",
      titleEn: "Caramelo",
      titleAr: "كاراميلو",
      descriptionEn: "Caramel Latte, double espresso and Fresh Milk",
      descriptionAr: "كاراميل لاتيه، إسبريسو مضاعف وحليب طازج",
      image: "/images/products/coffee.webp",
      protein: "5g",
      carbs: "42g",
      fat: "9g",
      kcal: 270,
      price: 2.25,
      available: true,
    },
    {
      id: "cof-12",
      titleEn: "White Mocha Latte",
      titleAr: "وايت موكا لاتيه",
      descriptionEn: "White chocolate latte, double espresso, fresh milk",
      descriptionAr: "لاتيه شوكولاتة بيضاء، إسبريسو مضاعف، حليب طازج",
      image: "/images/products/coffee.webp",
      protein: "5g",
      carbs: "36g",
      fat: "9g",
      kcal: 245,
      price: 2.25,
      available: true,
    },
    {
      id: "cof-13",
      titleEn: "Vanilla Shaken",
      titleAr: "فانيلا شيكن",
      descriptionEn: "Vanilla, double espresso, milk",
      descriptionAr: "فانيلا، إسبريسو مضاعف، حليب",
      image: "/images/products/coffee.webp",
      protein: "5g",
      carbs: "26g",
      fat: "7g",
      kcal: 185,
      price: 2.25,
      available: true,
    },
  ],
};

// 11. Tea & Specialty
export const teaSpecialty: MenuSectionData = {
  id: "tea-specialty",
  number: "11",
  titleEn: "Tea & Specialty",
  titleAr: "الشاي والمشروبات المختصة",
  backgroundColor: "#DCE5D1",
  accentColor: "#2A3D1E",
  image: "/images/products/tea.webp",
  items: [
    {
      id: "ts-1",
      titleEn: "Peach Iced Tea",
      titleAr: "شاي أيسد بخوخ",
      descriptionEn: "Black tea, peach, lemon",
      descriptionAr: "شاي أسود، خوخ، ليمون",
      image: "/images/products/tea.webp",
      protein: "0g",
      carbs: "26g",
      fat: "0g",
      kcal: 105,
      price: 2.0,
      available: true,
    },
    {
      id: "ts-2",
      titleEn: "Berries Iced Tea",
      titleAr: "شاي أيسد بالتوت",
      descriptionEn: "Black tea, mixed berries, lemon",
      descriptionAr: "شاي أسود، توت مشكل، ليمون",
      image: "/images/products/tea.webp",
      protein: "0g",
      carbs: "26g",
      fat: "0g",
      kcal: 105,
      price: 2.0,
      available: true,
    },
    {
      id: "ts-3",
      titleEn: "Green Lemonade",
      titleAr: "جرين ليموناضة",
      descriptionEn: "Lemon, Mint",
      descriptionAr: "ليمون، نعناع",
      image: "/images/products/tea.webp",
      protein: "0g",
      carbs: "38g",
      fat: "0g",
      kcal: 120,
      price: 2.0,
      available: true,
    },
    {
      id: "ts-4",
      titleEn: "Matcha Latte",
      titleAr: "ماتشا لاتيه",
      descriptionEn: "Matcha, fresh milk",
      descriptionAr: "ماتشا، حليب طازج",
      image: "/images/products/tea.webp",
      protein: "5g",
      carbs: "32g",
      fat: "9g",
      kcal: 230,
      price: 2.75,
      available: true,
    },
    {
      id: "ts-5",
      titleEn: "Pecan Protein Shake (Regular)",
      titleAr: "بروتين شيك بيكان (وسط)",
      descriptionEn: "Milk, whey protein, pecan and honey",
      descriptionAr: "حليب، ويه بروتين، جوز البيكان وعسل",
      image: "/images/products/tea.webp",
      protein: "30g",
      carbs: "30g",
      fat: "18g",
      kcal: 400,
      price: 3.5,
      available: true,
    },
    {
      id: "ts-6",
      titleEn: "Pecan Protein Shake (Small)",
      titleAr: "بروتين شيك بيكان (صغير)",
      descriptionEn: "Milk, whey protein, pecan and honey",
      descriptionAr: "حليب، ويه بروتين، جوز البيكان وعسل",
      image: "/images/products/tea.webp",
      protein: "20g",
      carbs: "20g",
      fat: "12g",
      kcal: 270,
      price: 2.95,
      available: true,
    },
  ],
};

// 12. Bowls
export const bowls: MenuSectionData = {
  id: "bowls",
  number: "12",
  titleEn: "Bowls",
  titleAr: "الباولز",
  backgroundColor: "#F5E9CE",
  accentColor: "#6B4918",
  image: "/images/products/bowls.webp",
  items: [
    {
      id: "bw-1",
      titleEn: "Tropical Yogurt Bowl",
      titleAr: "وعاء زبادي استوائي",
      descriptionEn: "Mix berries, granola, greek yogurt",
      descriptionAr: "توت مشكل، جرانولا، زبادي يوناني",
      image: "/images/products/bowls.webp",
      protein: "16g",
      carbs: "52g",
      fat: "10g",
      kcal: 360,
      price: 3.5,
      available: true,
    },
    {
      id: "bw-2",
      titleEn: "Pistachio Yogurt Bowl",
      titleAr: "وعاء زبادي بالفستق",
      descriptionEn: "Pistachio, granola, greek yogurt",
      descriptionAr: "فستق، جرانولا، زبادي يوناني",
      image: "/images/products/bowls.webp",
      protein: "28g",
      carbs: "58g",
      fat: "20g",
      kcal: 490,
      price: 3.95,
      available: true,
    },
  ],
};

// 13. Pastries
export const pastries: MenuSectionData = {
  id: "pastries",
  number: "13",
  titleEn: "Pastries",
  titleAr: "المخبوزات",
  backgroundColor: "#F2DFCB",
  accentColor: "#5E381A",
  image: "/images/products/pastries.webp",
  items: [
    {
      id: "pas-1",
      titleEn: "Milk Chocolate Cookies",
      titleAr: "كوكيز شوكولاتة بالحليب",
      descriptionEn: "Cookies dough, milk chocolate light butter",
      descriptionAr: "عجينة كوكيز، شوكولاتة بالحليب وزبدة خفيفة",
      image: "/images/products/pastries.webp",
      protein: "2g",
      carbs: "28g",
      fat: "10g",
      kcal: 210,
      price: 1.5,
      available: true,
    },
    {
      id: "pas-2",
      titleEn: "Pecan Protein Balls",
      titleAr: "كرات بروتين البيكان",
      descriptionEn: "Whey Protein Powder, Pecan, Biscuit, Chocolate",
      descriptionAr: "بودرة ويه بروتين، جوز البيكان، بسكويت وشوكولاتة",
      image: "/images/products/pastries.webp",
      protein: "16g",
      carbs: "12g",
      fat: "12g",
      kcal: 220,
      price: 1.75,
      available: true,
    },
    {
      id: "pas-3",
      titleEn: "Peanut Protein Balls",
      titleAr: "كرات بروتين زبدة الفول السوداني",
      descriptionEn: "Whey Protein Powder, Peanut Butter, Biscuit, Chocolate",
      descriptionAr: "بودرة ويه بروتين، زبدة فول سوداني، بسكويت وشوكولاتة",
      image: "/images/products/pastries.webp",
      protein: "16g",
      carbs: "12g",
      fat: "12g",
      kcal: 220,
      price: 1.75,
      available: true,
    },
    {
      id: "pas-4",
      titleEn: "Almond Protein Dates",
      titleAr: "تمر بالبروتين واللوز",
      descriptionEn: "Whey Protein Powder, dates, biscuit, almond",
      descriptionAr: "بودرة ويه بروتين، تمر، بسكويت ولوز",
      image: "/images/products/pastries.webp",
      protein: "12g",
      carbs: "28g",
      fat: "8g",
      kcal: 232,
      price: 1.75,
      available: true,
    },
    {
      id: "pas-5",
      titleEn: "Dark Chocolate Cookies",
      titleAr: "كوكيز شوكولاتة داكنة",
      descriptionEn: "Cookies dough dark chocolate, light butter",
      descriptionAr: "عجينة كوكيز شوكولاتة داكنة وزبدة خفيفة",
      image: "/images/products/pastries.webp",
      protein: "2g",
      carbs: "24g",
      fat: "9g",
      kcal: 185,
      price: 1.5,
      available: true,
    },
    {
      id: "pas-6",
      titleEn: "Moroccan Cookies",
      titleAr: "كوكيز مغربية",
      descriptionEn: "Walnut, cookies dough, icing sugar",
      descriptionAr: "عين الجمل، عجينة كوكيز وسكر بودرة",
      image: "/images/products/pastries.webp",
      protein: "4g",
      carbs: "18g",
      fat: "10g",
      kcal: 180,
      price: 1.5,
      available: true,
    },
    {
      id: "pas-7",
      titleEn: "Kinder Bites",
      titleAr: "قطع كيندر",
      descriptionEn: "Cookies dough, kinder",
      descriptionAr: "عجينة كوكيز وشوكولاتة كيندر",
      image: "/images/products/pastries.webp",
      protein: "1g",
      carbs: "18g",
      fat: "2g",
      kcal: 140,
      price: 1.5,
      available: true,
    },
    {
      id: "pas-8",
      titleEn: "Date Muffin",
      titleAr: "مافن التمر",
      descriptionEn: "Spongy cake, date, light butter",
      descriptionAr: "كيكة إسفنجية، تمر وزبدة خفيفة",
      image: "/images/products/pastries.webp",
      protein: "8g",
      carbs: "20g",
      fat: "6g",
      kcal: 185,
      price: 1.75,
      available: true,
    },
  ],
};

// 14. Classic Soft Serve
export const classicSoftServe: MenuSectionData = {
  id: "classic-soft-serve",
  number: "14",
  titleEn: "Classic Soft Serve",
  titleAr: "السوفت سيرف الكلاسيكي",
  backgroundColor: "#FAF1CD",
  accentColor: "#614916",
  image: "/images/products/softserve.webp",
  items: [
    {
      id: "css-1",
      titleEn: "Skinny Vanilla",
      titleAr: "سكيني فانيلا",
      descriptionEn: "Vanilla and milk",
      descriptionAr: "فانيلا وحليب",
      image: "/images/products/softserve.webp",
      protein: "4g",
      carbs: "30g",
      fat: "4g",
      kcal: 175,
      price: 2.25,
      available: true,
    },
    {
      id: "css-2",
      titleEn: "Equalush Soft Serve",
      titleAr: "سوفت سيرف إيكوالاش",
      descriptionEn: "Mango and passion fruit",
      descriptionAr: "مانجو وباDirectory فروت",
      image: "/images/products/softserve.webp",
      protein: "0g",
      carbs: "36g",
      fat: "0g",
      kcal: 180,
      price: 2.5,
      available: true,
    },
    {
      id: "css-3",
      titleEn: "Mango Vanilla Mix Swirl",
      titleAr: "مكس مانجو وفانيلا",
      descriptionEn: "Mango, passion fruit and vanilla",
      descriptionAr: "مانجو، باDirectory فروت وفانيلا",
      image: "/images/products/softserve.webp",
      protein: "3g",
      carbs: "36g",
      fat: "2g",
      kcal: 188,
      price: 2.5,
      available: true,
    },
    {
      id: "css-4",
      titleEn: "Greek Yogurt Classic",
      titleAr: "زبادي يوناني كلاسيك",
      descriptionEn: "Greek yogurt classic soft serve",
      descriptionAr: "سوفت سيرف الزبادي اليوناني الكلاسيكي",
      image: "/images/products/softserve.webp",
      protein: "13g",
      carbs: "23g",
      fat: "5g",
      kcal: 185,
      price: 2.5,
      available: true,
    },
  ],
};

// 15. Signature Soft Serve
export const signatureSoftServe: MenuSectionData = {
  id: "signature-soft-serve",
  number: "15",
  titleEn: "Signature Soft Serve",
  titleAr: "السوفت سيرف المميز",
  backgroundColor: "#FBE9BF",
  accentColor: "#573A10",
  image: "/images/products/signature-softserve.webp",
  items: [
    {
      id: "sss-1",
      titleEn: "Mango Cheesecake",
      titleAr: "مانجو تشيزكيك",
      descriptionEn: "Mango, passion fruit, vanilla, fresh mango, waffle and mango sauce",
      descriptionAr: "مانجو، باDirectory فروت، فانيلا، مانجو طازج، وافل وصلصة المانجو",
      image: "/images/products/signature-softserve.webp",
      protein: "3g",
      carbs: "38g",
      fat: "10g",
      kcal: 255,
      price: 3.25,
      available: true,
    },
    {
      id: "sss-2",
      titleEn: "Vanilla Almond",
      titleAr: "فانيلا باللوز",
      descriptionEn: "Vanilla, almond and caramel",
      descriptionAr: "فانيلا، لوز وكاراميل",
      image: "/images/products/signature-softserve.webp",
      protein: "8g",
      carbs: "37g",
      fat: "14g",
      kcal: 305,
      price: 3.25,
      available: true,
    },
    {
      id: "sss-3",
      titleEn: "Pecan Crunch",
      titleAr: "بيكان كرنش",
      descriptionEn: "Vanilla, roasted pecan and biscuit sauce",
      descriptionAr: "فانيلا، جوز البيكان المحمص وصلصة البسكويت",
      image: "/images/products/signature-softserve.webp",
      protein: "6g",
      carbs: "38g",
      fat: "14g",
      kcal: 300,
      price: 3.25,
      available: true,
    },
    {
      id: "sss-4",
      titleEn: "Vanilla & Cookies",
      titleAr: "فانيلا وكوكيز",
      descriptionEn: "Vanilla, chocolate biscuit and toffee",
      descriptionAr: "فانيلا، بسكويت شوكولاتة وتوفي",
      image: "/images/products/signature-softserve.webp",
      protein: "4g",
      carbs: "33g",
      fat: "14g",
      kcal: 275,
      price: 3.0,
      available: true,
    },
    {
      id: "sss-5",
      titleEn: "Mango Greek Yogurt",
      titleAr: "زبادي يوناني بالمانجو",
      descriptionEn: "Greek yogurt, whey protein, stevia, fresh mango, mango sauce and biscuit",
      descriptionAr: "زبادي يوناني، ويه بروتين، ستيفيا، مانجو طازج، صلصة المانجو وبسكويت",
      image: "/images/products/signature-softserve.webp",
      protein: "13g",
      carbs: "30g",
      fat: "8g",
      kcal: 245,
      price: 3.5,
      available: true,
    },
    {
      id: "sss-6",
      titleEn: "Berries Greek Yogurt",
      titleAr: "زبادي يوناني بالتوت",
      descriptionEn: "Greek yogurt, whey protein, stevia, fresh mixed berries, berries sauce and biscuit",
      descriptionAr: "زبادي يوناني، ويه بروتين، ستيفيا، توت طازج مشكل، صلصة التوت وبسكويت",
      image: "/images/products/signature-softserve.webp",
      protein: "13g",
      carbs: "30g",
      fat: "8g",
      kcal: 245,
      price: 3.5,
      available: true,
    },
    {
      id: "sss-7",
      titleEn: "Pistachio Greek Yogurt",
      titleAr: "زبادي يوناني بالفستق",
      descriptionEn: "Greek yogurt, whey protein, stevia, crushed pistachio and pistachio sauce",
      descriptionAr: "زبادي يوناني، ويه بروتين، ستيفيا، فستق مطحون وصلصة الفستق",
      image: "/images/products/signature-softserve.webp",
      protein: "20g",
      carbs: "38g",
      fat: "14g",
      kcal: 360,
      price: 3.75,
      available: true,
    },
  ],
};

// Complete Master Array including all 15 categories in original design order
export const menuSections: MenuSectionData[] = [
  savoryPots,
  sweetPots,
  salads,
  sandwichesWraps,
  bunsTacos,
  plates,
  juices,
  detox,
  lushies,
  coffee,
  teaSpecialty,
  bowls,
  pastries,
  classicSoftServe,
  signatureSoftServe,
];