import { MenuIntroData } from "./menuIntro.types";

export const menuIntroData: MenuIntroData = {
  sectionNumber: "§ 02",

  sectionTitleEn: "TABLE OF CONTENTS — THE MENU",
  sectionTitleAr: "جدول المحتويات — القائمة",

  headingLine1En: "From morning into night,",
  headingLine2En: "one long sit.",

  headingLine1Ar: "من الصباح حتى المساء،",
  headingLine2Ar: "جلسة طويلة واحدة.",

  buttonEn: "Open the Menu",
  buttonAr: "افتح القائمة",

  items: [
    {
      id: 1,
      number: "01",
      titleEn: "Savory Pots",
      titleAr: "بوتس مالحة",
      image: "/images/products/pecan.webp",
      dotColor: "#9BB068",
      descriptionEn: "Layered and spooned, built to graze.",
      descriptionAr: "طبقات غنية، مُعدّة للاستمتاع.",
      captionEn: "The morning counter.",
      captionAr: "منصة الصباح.",
    },
    {
      id: 2,
      number: "02",
      titleEn: "Sweet Pots",
      titleAr: "بوتس حلوة",
      image: "/images/products/matcha.webp",
      dotColor: "#DD9948",
      descriptionEn: "Morning sugar, kept honest.",
      descriptionAr: "حلاوة الصباح، بنكهة صادقة.",
      captionEn: "Sweet morning flavors.",
      captionAr: "نكهات الصباح الحلوة.",
    },
    {
      id: 3,
      number: "03",
      titleEn: "Salads",
      titleAr: "سلطات",
      image: "/images/products/acai.webp",
      dotColor: "#8FA45B",
      descriptionEn: "Crisp, bright, generous.",
      descriptionAr: "مقرمشة، طازجة، ووفيرة.",
      captionEn: "Fresh greens.",
      captionAr: "خضار طازجة.",
    },
    {
      id: 4,
      number: "04",
      titleEn: "Sandwiches & Wraps",
      titleAr: "سندويشات وراب",
      image: "/images/products/iced-espresso.webp",
      dotColor: "#E2B27A",
      descriptionEn: "Pressed, stacked, never compromised.",
      descriptionAr: "مكبوسة ومحشوة بعناية فائقة.",
      captionEn: "Handcrafted sandwiches.",
      captionAr: "شطائر صُنعت يدويًا.",
    },
    {
      id: 5,
      number: "05",
      titleEn: "Buns & Tacos",
      titleAr: "صمون وتاكو",
      image: "/images/products/pecan.webp",
      dotColor: "#D1C399",
      descriptionEn: "Handheld, sauces on the side.",
      descriptionAr: "تؤكل باليد، مع الصلصات الجانبية.",
      captionEn: "Warm buns.",
      captionAr: "صمون دافئ.",
    },
    {
      id: 6,
      number: "06",
      titleEn: "Plates",
      titleAr: "أطباق",
      image: "/images/products/matcha.webp",
      dotColor: "#A1B475",
      descriptionEn: "The full-sit down, midday to evening.",
      descriptionAr: "الوجبة الكاملة، من الظهيرة حتى المساء.",
      captionEn: "Signature lunch plates.",
      captionAr: "أطباق الغداء المميزة.",
    },
    {
      id: 7,
      number: "07",
      titleEn: "Juices",
      titleAr: "عصائر",
      image: "/images/products/acai.webp",
      dotColor: "#C7D442",
      descriptionEn: "Freshly squeezed daily.",
      descriptionAr: "عصائر طازجة يومياً.",
      captionEn: "Ice-cold refreshments.",
      captionAr: "مرطبات باردة.",
    },
    {
      id: 8,
      number: "08",
      titleEn: "Detox",
      titleAr: "ديتوكس",
      image: "/images/products/iced-espresso.webp",
      dotColor: "#8FA45B",
      descriptionEn: "Cleanse and revitalize.",
      descriptionAr: "لتنقية وتجديد النشاط.",
      captionEn: "Pure elements.",
      captionAr: "عناصر نقية.",
    },
    {
      id: 9,
      number: "09",
      titleEn: "Lushies",
      titleAr: "لاشيز",
      image: "/images/products/pecan.webp",
      dotColor: "#E2B27A",
      descriptionEn: "Blended frozen treats.",
      descriptionAr: "مشروبات مثلجة ومخلوطة.",
      captionEn: "Frozen blends.",
      captionAr: "خلطات مثلجة.",
    },
    {
      id: 10,
      number: "10",
      titleEn: "Coffee",
      titleAr: "قهوة",
      image: "/images/products/matcha.webp",
      dotColor: "#D1C399",
      descriptionEn: "Artisanal espresso extractions.",
      descriptionAr: "إسبريسو مُعدّ بحرفية.",
      captionEn: "Daily brew.",
      captionAr: "قهوة اليوم.",
    },
    {
      id: 11,
      number: "11",
      titleEn: "Tea & Specialty",
      titleAr: "مشروبات",
      image: "/images/products/acai.webp",
      dotColor: "#A1B475",
      descriptionEn: "Curated organic loose leaves.",
      descriptionAr: "أوراق شاي عضوية منتقاة.",
      captionEn: "Infused specialties.",
      captionAr: "مشروبات دافئة مميزة.",
    },
    {
      id: 12,
      number: "12",
      titleEn: "Bowls",
      titleAr: "طبقات باردة",
      image: "/images/products/iced-espresso.webp",
      dotColor: "#9BB068",
      descriptionEn: "Chilled wholesome bases.",
      descriptionAr: "مكونات صحية مبردة.",
      captionEn: "Nutritious mix.",
      captionAr: "مزيج غني بالطاقة.",
    },
    {
      id: 13,
      number: "13",
      titleEn: "Pastries",
      titleAr: "مخبوزات",
      image: "/images/products/pecan.webp",
      dotColor: "#DD9948",
      descriptionEn: "Baked fresh every morning.",
      descriptionAr: "مخبوزات طازجة كل صباح.",
      captionEn: "Flaky golden bakes.",
      captionAr: "مخبوزات ذهبية وهشة.",
    },
    {
      id: 14,
      number: "14",
      titleEn: "Classic Soft Serve",
      titleAr: "سوفت سيرف كلاسيك",
      image: "/images/products/matcha.webp",
      dotColor: "#E2B27A",
      descriptionEn: "Timeless creamy textures.",
      descriptionAr: "قوام كريمي كلاسيكي.",
      captionEn: "Pure vanilla and chocolate.",
      captionAr: "فانيلا وشوكولاتة صافية.",
    },
    {
      id: 15,
      number: "15",
      titleEn: "Signature Soft Serve",
      titleAr: "سوفت سيرف أناناس",
      image: "/images/products/acai.webp",
      dotColor: "#C7D442",
      descriptionEn: "Infused with our signature touch.",
      descriptionAr: "مُعدّ بلمستنا الخاصة.",
      captionEn: "The true house special.",
      captionAr: "الحلوى المميزة الخاصة بنا.",
    },
  ],
};