import { BranchesData } from "./branches.types";

export const branchesData: BranchesData = {
  sectionNumber: "§ 03",

  sectionTitleEn: "OUR BRANCHES — ACROSS KUWAIT",
  sectionTitleAr: "فروعنا — في أنحاء الكويت",

  headingLine1En: "A familiar welcome",
  headingLine2En: "at every address.",

  headingLine1Ar: "ترحيب مألوف",
  headingLine2Ar: "في كل عنوان.",

  branches: [
  {
    id: 1,
    titleEn: "Kuwait City",
    titleAr: "مدينة الكويت",
    locationEn: "Salhiya St, next to SimSim & Mana",
    locationAr: "شارع الصالحية، بجوار سمسم ومانا",
    image: "/images/branches/store1.webp",
    href: "/locations/",
  },
  {
    id: 2,
    titleEn: "Jabriya",
    titleAr: "الجابرية",
    locationEn: "Building 180, 105 St, Jabriya",
    locationAr: "مبنى ١٨٠، شارع ١٠٥، الجابرية",
    image: "/images/branches/store2.webp",
    href: "/locations/",
  },
  {
    id: 3,
    titleEn: "Al Qurain",
    titleAr: "القرين",
    locationEn: "Salwa Walk, Block 6",
    locationAr: "سالوا ووك، قطعة ٦",
    image: "/images/branches/store3.webp",
    href: "/locations/",
  },
  {
    id: 4,
    titleEn: "Aswaq Qurain",
    titleAr: "أسواق القرين",
    locationEn: "Address coming soon",
    locationAr: "العنوان قريباً",
    image: "/images/branches/store4.webp",
    href: "/locations/",
  },
  {
    id: 5,
    titleEn: "Adailiya",
    titleAr: "العديلية",
    locationEn: "Block 4, Avenue 4",
    locationAr: "قطعة ٤، شارع ٤",
    image: "/images/branches/store5.webp",
    href: "/locations/",
  },
  {
    id: 6,
    titleEn: "Shuwaikh",
    titleAr: "الشويخ",
    locationEn: "Address coming soon",
    locationAr: "العنوان قريباً",
    image: "/images/branches/store6.webp",
    href: "/locations/",
  },
  {
    id: 7,
    titleEn: "Murouj",
    titleAr: "المروج",
    locationEn: "Murouj Complex",
    locationAr: "مجمع المروج",
    image: "/images/branches/store7.webp",
    href: "/locations/",
  },
  {
    id: 8,
    titleEn: "Mishref",
    titleAr: "المشرف",
    locationEn: "Yarmouk Club",
    locationAr: "نادي اليرموك",
    image: "/images/branches/store8.webp",
    href: "/locations/",
  },
  {
    id: 9,
    titleEn: "Messilah",
    titleAr: "المسيلة",
    locationEn: "Next to Messilah Beach Hotel",
    locationAr: "بجوار فندق المسيلة بيتش",
    image: "/images/branches/store9.webp",
    href: "/locations/",
  },
  {
    id: 10,
    titleEn: "Bnaider",
    titleAr: "بنيدر",
    locationEn: "Al Ad'ami, South Kuwait",
    locationAr: "العدامي، جنوب الكويت",
    image: "/images/branches/store10.webp",
    href: "/locations/",
  },
  {
    id: 11,
    titleEn: "Jahra",
    titleAr: "الجهراء",
    locationEn: "Address coming soon",
    locationAr: "العنوان قريباً",
    image: "/images/branches/store11.webp",
    href: "/locations/",
  },
  {
    id: 12,
    titleEn: "Avenues Mall",
    titleAr: "مجمّع الأفنيوز",
    locationEn: "The Avenues Mall",
    locationAr: "مجمع الأفنيوز",
    image: "/images/branches/store12.webp",
    href: "/locations/",
  },
],
};