import { Location } from "./locations.types";

export const locations: Location[] = [
  {
    id: "kuwait-city",
    name: "Kuwait City",
    name_ar: "مدينة الكويت",
    addr: "Salhiya St, next to SimSim & Mana",
    addr_ar: "شارع الصالحية، بجوار سمسم ومانا",
    hours: "7:00 — 23:00 daily",
    hours_ar: "٧:٠٠ — ٢٣:٠٠ يومياً",
    tag: {
      en: "City",
      ar: "المدينة",
    },
    img: "/images/branches/store1.webp",
    amenities: ["dine-in", "outdoor", "delivery", "simsim"],
    note: {
      en: "Big windows on Salhiya Street, between SimSim and Mana. Open from breakfast through the evening.",
      ar: "نوافذٌ كبيرة على شارع الصالحية، بين سمسم ومانا. مفتوحٌ من الفطور حتى المساء.",
    },
    coords: {
      lat: 29.3759,
      lng: 47.9774,
    },
  },
  {
    id: "jabriya",
    name: "Jabriya",
    name_ar: "الجابرية",
    addr: "Building 180, 105 St, Jabriya",
    addr_ar: "مبنى ١٨٠، شارع ١٠٥، الجابرية",
    hours: "6:00 — 1:00 daily",
    hours_ar: "٦:٠٠ — ١:٠٠ يومياً",
    tag: {
      en: "Neighborhood",
      ar: "حي",
    },
    img: "/images/branches/store2.webp",
    amenities: ["dine-in", "outdoor", "delivery", "simsim"],
    note: {
      en: "A neighborhood room. Wide terrace outside, regulars who claim the corner banquette.",
      ar: "غرفة الحي. تراسٌ واسع بالخارج، روّادٌ يحتلّون الزاوية.",
    },
    coords: {
      lat: 29.3163,
      lng: 48.0247,
    },
  },
  {
    id: "qurain-walk",
    name: "Al Qurain",
    name_ar: "القرين",
    addr: "Salwa Walk, Block 6, Qurain",
    addr_ar: "سالوا ووك، قطعة ٦، القرين",
    hours: "6:00 — 24:00 daily",
    hours_ar: "٦:٠٠ — ٢٤:٠٠ يومياً",
    tag: {
      en: "Promenade",
      ar: "ممشى",
    },
    img: "/images/branches/store3.webp",
    amenities: ["dine-in", "outdoor", "delivery"],
    note: {
      en: "On the walking strip. Long benches outside, a breeze most evenings.",
      ar: "على شريط المشي. مقاعد طويلة بالخارج، نسمةٌ معظم الأمسيات.",
    },
    coords: {
      lat: 29.2129,
      lng: 48.0997,
    },
  },
  {
    id: "aswaq-qurain",
    name: "Aswaq Qurain",
    name_ar: "أسواق القرين",
    addr: "Address coming soon",
    addr_ar: "العنوان قريباً",
    hours: "6am — 2am daily",
    hours_ar: "٦ صباحاً — ٢ فجراً يومياً",
    tag: {
      en: "Marketplace",
      ar: "الأسواق",
    },
    img: "/images/branches/store4.webp",
    amenities: ["dine-in", "delivery", "simsim"],
    note: {
      en: "A quieter room inside the marketplace. Details coming together — call ahead while we settle in.",
      ar: "غرفةٌ أهدأ داخل الأسواق. التفاصيل تكتمل — اتصل قبل القدوم بينما نستقرّ.",
    },
    coords: {
      lat: 29.2074,
      lng: 48.1015,
    },
  },
  {
    id: "adailiya",
    name: "Adailiya",
    name_ar: "العديلية",
    addr: "Block 4, Avenue 4, Adailiya",
    addr_ar: "قطعة ٤، شارع ٤، العديلية",
    hours: "6:00 — 24:00 daily",
    hours_ar: "٦:٠٠ — ٢٤:٠٠ يومياً",
    tag: {
      en: "Garden",
      ar: "حديقة",
    },
    img: "/images/branches/store5.webp",
    amenities: ["dine-in", "outdoor", "delivery"],
    note: {
      en: "Tucked off the avenue. Small room, big windows, garden chairs out the back.",
      ar: "مخبّأٌ خلف الشارع. غرفةٌ صغيرة، نوافذٌ كبيرة، وكراسي حديقةٍ في الخلف.",
    },
    coords: {
      lat: 29.3461,
      lng: 47.9543,
    },
  },
  {
    id: "shuwaikh",
    name: "Shuwaikh",
    name_ar: "الشويخ",
    addr: "Address coming soon",
    addr_ar: "العنوان قريباً",
    hours: "6am — 2am daily",
    hours_ar: "٦ صباحاً — ٢ فجراً يومياً",
    tag: {
      en: "Industrial",
      ar: "صناعي",
    },
    img: "/images/branches/store6.webp",
    amenities: ["dine-in", "outdoor", "delivery"],
    note: {
      en: "On a Shuwaikh side street — green facade, awnings, palms. Details coming together; call ahead while we settle in.",
      ar: "في شارعٍ جانبي بالشويخ — واجهةٌ خضراء، مظلّات، ونخيل. التفاصيل تكتمل — اتصل قبل القدوم بينما نستقرّ.",
    },
    coords: {
      lat: 29.3411,
      lng: 47.9315,
    },
  },
  {
    id: "murouj",
    name: "Murouj",
    name_ar: "المروج",
    addr: "Murouj Complex, Block 3",
    addr_ar: "مجمّع المروج، قطعة ٣",
    hours: "7:00 — 23:00 daily",
    hours_ar: "٧:٠٠ — ٢٣:٠٠ يومياً",
    tag: {
      en: "Complex",
      ar: "مجمّع",
    },
    img: "/images/branches/store7.webp",
    amenities: ["dine-in", "delivery", "simsim"],
    note: {
      en: "Inside the complex — a quieter pace, the full pastry case, the long pour.",
      ar: "داخل المجمّع — وتيرةٌ أهدأ، المخبوزات كاملة، والصبّ طويل.",
    },
    coords: {
      lat: 29.2913,
      lng: 47.942,
    },
  },
  {
    id: "mishref",
    name: "Mishref",
    name_ar: "المشرف",
    addr: "Yarmouk Club, Mishref",
    addr_ar: "نادي اليرموك، المشرف",
    hours: "6:00 — 24:00 daily",
    hours_ar: "٦:٠٠ — ٢٤:٠٠ يومياً",
    tag: {
      en: "Club",
      ar: "نادٍ",
    },
    img: "/images/branches/store8.webp",
    amenities: ["dine-in", "outdoor", "delivery"],
    note: {
      en: "Beside the Yarmouk Club. Open early, open late, busiest at the end of a match.",
      ar: "بجوار نادي اليرموك. مفتوحٌ مبكراً ومتأخراً، أزحم وقتٍ هو نهاية المباراة.",
    },
    coords: {
      lat: 29.2706,
      lng: 48.081,
    },
  },
  {
    id: "messilah",
    name: "Messilah",
    name_ar: "المسيلة",
    addr: "Next to Messilah Beach Hotel, Messilah",
    addr_ar: "بجوار فندق المسيلة بيتش، المسيلة",
    hours: "6:00 — 2:00 daily",
    hours_ar: "٦:٠٠ — ٢:٠٠ يومياً",
    tag: {
      en: "Beachside",
      ar: "على البحر",
    },
    img: "/images/branches/store9.webp",
    amenities: ["dine-in", "outdoor", "delivery", "simsim"],
    note: {
      en: "A few steps from the beach hotel. Breakfast through past midnight, the sea always nearby.",
      ar: "خطواتٌ من الفندق على البحر. من الفطور حتى ما بعد منتصف الليل، والبحر دائماً قريب.",
    },
    coords: {
      lat: 29.2806,
      lng: 48.1093,
    },
  },
  {
    id: "bnaider",
    name: "Bnaider",
    name_ar: "بنيدر",
    addr: "Al Ad'ami, south Kuwait",
    addr_ar: "العدامي، جنوب الكويت",
    hours: "6:00 — 2:00 daily",
    hours_ar: "٦:٠٠ — ٢:٠0 يومياً",
    tag: {
      en: "Coastal",
      ar: "ساحلي",
    },
    img: "/images/branches/store10.webp",
    amenities: ["dine-in", "outdoor", "delivery"],
    note: {
      en: "South of the city, on the way to the coast. Long hours for long drives.",
      ar: "جنوب المدينة، في الطريق إلى الساحل. ساعاتٌ طويلة لسفراتٍ طويلة.",
    },
    coords: {
      lat: 28.6515,
      lng: 48.3215,
    },
  },
  {
    id: "jahra",
    name: "Jahra",
    name_ar: "الجهراء",
    addr: "Jahra Mall, Jahra",
    addr_ar: "الجهراء مول، الجهراء",
    hours: "6:00 — 1:00 daily",
    hours_ar: "٦:٠٠ — ١:٠٠ يومياً",
    tag: {
      en: "Mall",
      ar: "مول",
    },
    img: "/images/branches/store11.webp",
    amenities: ["dine-in", "delivery", "simsim"],
    note: {
      en: "Inside Jahra Mall. A bright room for coffee, breakfast, and family gatherings.",
      ar: "داخل الجهراء مول. مكانٌ مشرق للقهوة والفطور واجتماعات العائلة.",
    },
    coords: {
      lat: 29.3375,
      lng: 47.6584,
    },
  },
  {
    id: "saad-alabdullah",
    name: "Saad Al Abdullah",
    name_ar: "سعد العبدالله",
    addr: "Block 8, Saad Al Abdullah",
    addr_ar: "قطعة ٨، سعد العبدالله",
    hours: "6:00 — 24:00 daily",
    hours_ar: "٦:٠٠ — ٢٤:٠٠ يومياً",
    tag: {
      en: "Residential",
      ar: "سكني",
    },
    img: "/images/branches/store12.webp",
    amenities: ["dine-in", "outdoor", "delivery"],
    note: {
      en: "A calm neighborhood branch with indoor seating and outdoor tables.",
      ar: "فرعٌ هادئ داخل المنطقة السكنية مع جلسات داخلية وخارجية.",
    },
    coords: {
      lat: 29.3652,
      lng: 47.6938,
    },
  },
  {
    id: "avenues",
    name: "The Avenues",
    name_ar: "الأفنيوز",
    addr: "The Avenues Mall, Phase 4",
    addr_ar: "الأفنيوز، المرحلة الرابعة",
    hours: "10:00 — 24:00 daily",
    hours_ar: "١٠:٠٠ — ٢٤:٠٠ يومياً",
    tag: {
      en: "Shopping Mall",
      ar: "مركز تسوق",
    },
    img: "/images/branches/store1.webp", // Wraps back to store1 for the 13th item
    amenities: ["dine-in", "delivery", "simsim"],
    note: {
      en: "Located inside The Avenues with our full coffee menu, desserts, and signature drinks.",
      ar: "داخل مجمع الأفنيوز مع كامل قائمة القهوة والحلويات والمشروبات المميزة.",
    },
    coords: {
      lat: 29.3033,
      lng: 47.9328,
    },
  },
];